version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.16
  php:
    docker:
      - image: circleci/php:7.4.7

commands:
  say-hello:
    parameters:
      text:
        type: string
    steps:
      - run:
          name: Hello
          command: echo Hello << parameters.text >>

jobs:
  hello:
    parameters:
      username:
        type: string
        default: ""
      ex:
        type: executor
        default: node
    executor: << parameters.ex >>
    steps:
      - when:
          condition: << parameters.username >>
          steps:
            - say-hello:
                text: Core << parameters.username >>
      - unless:
          condition: << parameters.username >>
          steps:
            - say-hello:
                text: world

    

workflows:
  version: 2

  main-workflow:
    jobs:
      - hello:
          name: hello
      - hello:
          name: hello-chris
          username: "Chris"
          requires:
            - hello
      - hello:
          name: hello-romain
          username: "Romain"
          ex: php
          requires:
            - hello
