version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12

commands:
  say-hello:
    parameters:
      text:
        type: string
    steps:
      - run:
          name: 'Hello'
          command: echo "Hello << parameters.text >>"

jobs:
  hello:
    executor: node
    parameters:
      username:
        type: string
    steps:
      - say-hello:
          text: Core << parameters.username >>
    

workflows:
  version: 2

  main-workflow:
    jobs:
      - hello:
          name: hello-chris
          username: "Chris"
      - hello:
          name: hello-romain
          username: "Romain"
          requires:
            - hello-chris
